USE incarnate_gaming;
SHOW TABLES;
DROP TABLE incarnate_lore_citizen;
DROP TABLE incarnate_lore_subpoint;
DROP TABLE incarnate_lore_point_of_interest;
DROP TABLE incarnate_lore_buildings;
DROP TABLE incarnate_lore_district;
DROP TABLE incarnate_lore_city;
DROP TABLE incarnate_lore_state;
DROP TABLE incarnate_lore_country;
DROP TABLE incarnate_lore_planet;
DROP TABLE incarnate_lore_plane;
DROP TABLE incarnate_skill;
DROP TABLE incarnate_riddle;
DROP TABLE incarnate_race_subrace_trait;
DROP TABLE incarnate_race_subrace;
DROP TABLE incarnate_race_trait;
DROP TABLE incarnate_race;
DROP TABLE chapter_intro;
DROP TABLE incarnate_background_feature;
DROP TABLE incarnate_background;
DROP TABLE incarnate_class_archetype_trait;
DROP TABLE incarnate_class_archetype;
DROP TABLE incarnate_class_trait;
DROP TABLE incarnate_class;
DROP TABLE incarnate_equipment;
DROP TABLE incarnate_equipment_pack;
DROP TABLE incarnate_feat;
DROP TABLE incarnate_table;
DROP TABLE migration_versions;
DROP TABLE incarnate_item;
SHOW TABLES;