USE incarnate_gaming;
SHOW TABLES;
SELECT * from chapter_intro;
SELECT * from incarnate_background where id = 3188;
SELECT * from incarnate_background_feature;
SELECT * from incarnate_class;
SELECT * from incarnate_class_archetype;
SELECT * from incarnate_class_archetype_trait;
SELECT * from incarnate_class_trait;
SELECT * from incarnate_equipment;
SELECT * from incarnate_equipment_pack;
SELECT * from incarnate_feat;
SELECT * from incarnate_riddle;
SELECT * from incarnate_race;
SELECT * from incarnate_race_trait;
SELECT * from incarnate_race_subrace;
SELECT * from incarnate_race_subrace_trait;
SELECT * from incarnate_item WHERE id = 11163;
SELECT * from incarnate_table WHERE id = 1574;
SELECT * from migration_versions;