USE incarnate_gaming;
SHOW TABLES;
SELECT * FROM incarnate_lore_citizen;
SELECT * FROM incarnate_lore_subpoint;
SELECT * FROM incarnate_lore_point_of_interest;
SELECT * FROM incarnate_lore_buildings;
SELECT * FROM incarnate_lore_district;
SELECT * FROM incarnate_lore_city;
SELECT * FROM incarnate_lore_state;
SELECT * FROM incarnate_lore_country;
SELECT * FROM incarnate_lore_planet;
SELECT * FROM incarnate_lore_plane;
SELECT * from chapter_intro;
SELECT * from incarnate_background;
SELECT * from incarnate_background_feature;
SELECT * from incarnate_class;
SELECT * from incarnate_class_archetype;
SELECT * from incarnate_class_archetype_trait;
SELECT * from incarnate_class_trait;
SELECT * from incarnate_equipment;
SELECT * from incarnate_equipment_pack;
SELECT * from incarnate_feat;
SELECT * from incarnate_riddle;
SELECT * from incarnate_race;
SELECT * from incarnate_race_trait;
SELECT * from incarnate_race_subrace;
SELECT * from incarnate_race_subrace_trait;
SELECT * from incarnate_skill;
SELECT * from incarnate_item WHERE id >= 4267;
SELECT * from incarnate_item;
SELECT * from incarnate_table WHERE id = 1574;
SELECT * from migration_versions;
SELECT * from user;